### ISSUE TITLE
Commented by lxt

### ISSUE THREAD

**Issue by sjtu-XutongLu** [LeiHaoruo/NumGuess#1]
1. 较好的变量命名及格式。
2. 逻辑正确无误。
3. 然而答案的输出格式并不符合要求。
4. 输入检测可以做一下。

**Comment by Xu-yuan** [comment]
1 程序可读性很高
2 程序能够运行没有错误
3 输出格式应略作修改

**Comment by cpxdudu** [comment]
1、程序格式整齐，易于阅读
2、程序顺利运行，算法简便
3、考虑加入输入检测以免系统运行错误
